config/routes.rb
Rails.application.routes.draw do

   root 'welcome#index'

   get '/login' => 'sessions#new'
   post '/login' => 'sessions#create'
   get '/logout' => 'sessions#destroy' #, as: 'logout'

   get '/signup' => 'users#new' #, as: 'signup'
   post '/users' => 'users#create'

   resources :users

   resources :mixtapes do
      member do
         post 'record_song'
         get 'erase_song'
      end
   end

   resources :songs

end

app/models/user.rb
class User < ActiveRecord::Base
   has_secure_password

   has_many :mixtapes
   has_many :songs

   # can't be blank
   validates :dj_name, :email, presence: true

   # there can only be one #{dj_name}!
   validates :dj_name, uniqueness: {
      case_sensitive: false,
      message: "belongs to someone else, and there can only be one."
   }

   # one account per email address.
   validates :email, uniqueness: {
      case_sensitive: false,
      message: "is already associated with an account." }

   # string@string.string format for email
   validates :email, format: { with: /\A\S+@.+\.\S+\z/,
      message: "Your email should be in foo@bar.com format" }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   # before_filter :first_or_authenticated, only: [:index, :new, :create]

   # User must be logged in to add/edit account info
   # Unless they are the first user!

   # def first_or_authenticated
   #   unless User.count == 0 || current_user
   #     redirect_to root_path
   #     return false
   #   end
   # end

   def index
      @users = User.all
   end

   def new
   end

   def create
      @user = User.new(user_params)
      if @user.save
         flash.notice = "Welcome to Mix.r! Remember your DJ name #{@user.dj_name.upcase}, you will use it to login."
         render 'sessions/new'
      else
         render 'new'
      end
   end

   def edit
      @user = User.find(params[:id])
   end

   def update
      @user = User.find(params[:id])
      if @user.id != current_user.id
         flash.notice = "I don't know how you got here but EDIT YOUR OWN PROFILE! Jeez. Control freak much?"
         redirect_to user_path(current_user)
      elsif (@user.id == current_user.id) && @user.update(user_params)
         render user_path(@user)
      else
         flash.notice = "Your profile is updated!"
         redirect_to user_path(@user)
      end
   end

   def show
      @user = User.find(params[:id])
      @mixtapes = @user.mixtapes.order(created_at: :desc)
      @songs = @user.songs.order(created_at: :desc)
   end

   private

   def user_params
    params.require(:user).permit(:dj_name, :email, :avatar, :password, :password_confirmation)
   end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_my_mixtapes.html.erb
<% collection.each do |mixtape| %>
   <div class="tapes">
      <h1><%= link_to mixtape.name, mixtape_path(mixtape), class: 'mixtape_name', id: "mixtape_#{mixtape.id}" %></h1>
      <p>(<%= mixtape.songs.length %>) Songs about: <%= mixtape.about %></p>
      <p>Posted <%= distance_of_time_in_words(DateTime.now, mixtape.created_at) %> ago</p>
      <p>Edited <%= distance_of_time_in_words(DateTime.now, mixtape.updated_at) %> ago</p>
      <% if current_user %>
         <%= link_to 'Edit Mixtape Details', edit_mixtape_path(mixtape) %>
      <% end %>
   </div>
<% end %>

app/views/users/_my_songs.html.erb
<% collection.each do |song| %>
   <div class="songs">
      <p class="song-info"><span class="italic"><%= song.title %></span> by <%= song.artist %></p>
      <%= render partial: 'songs/play_button', :locals => { :song => song }%>
      <p class="links">
         <%= link_to "View Song Details", song_path(song) %>
         Posted <%= distance_of_time_in_words(DateTime.now, song.created_at) %> ago
         Edited <%= distance_of_time_in_words(DateTime.now, song.updated_at) %> ago
      </p>
   </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile:</h1>
<% if current_user && (@user.id != current_user.id) %>
   <p> You can only edit <%= link_to 'your own profile!', user_path(current_user) %> Duh! </p>
<% elsif current_user && (@user.id == current_user.id) %>
   <%= form_for :user do |f| %>
      <%= f.label "What's your new DJ name, yo?" %>
      <%= f.text_field :dj_name %>
      <br>

      <%= f.label "Enter a new avatar" %>
      <%= f.text_field :avatar %>
      <br>

      <%= f.label "New email address:" %>
      <%= f.text_field :email %>
      <br>

      <%= f.label "New password" %>
      <%= f.password_field :password %>
      <br>

      <%= f.label "One more time, just to be sure" %>
      <%= f.password_field :password_confirmation %>
      <br>

      <%= f.submit "Submit Changes" %>
   <% end %>
<% else %>
   <%# display nag to login when CREEPING as guest %>
   <p class="nag"> seriously though how tf did you get here? Stop sneaking around!
   <br><%= link_to 'LOGIN', '/login' %> or <%= link_to 'CREATE AN ACCOUNT', '/signup' %> ALREADY! :/</p>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
   <div class="user" id="<%= user.id %>">
      <h1>DJ: <%= user.dj_name %></h1>
      <%= image_tag user.avatar %>
      <p> View <%= user.dj_name %>'s <%= link_to 'Collection', user_path(user) %></p>
   </div>
<% end %>

app/views/users/new.html.erb
<h1>You can be a DJ too!</h1>

<% if !current_user %>
   <%= render partial: 'layouts/errors', :locals => { :noun => @user } %>

   <%= form_for :user, :html => {:class => 'create_user'}, url: '/users' do |f| %>
      <%= f.label "What's your DJ name, yo?" %>
      <%= f.text_field :dj_name %>
      <br>

      <%= f.label "Choose an image url as your avatar" %>
      <%= f.text_field :avatar %>
      <br>

      <%= f.label :email %>
      <%= f.text_field :email %>
      <br>

      <%= f.label "Enter your password" %>
      <%= f.password_field :password %>
      <br>

      <%= f.label "One more time, just to be sure" %>
      <%= f.password_field :password_confirmation %>
      <br>
      <%= f.submit "Create Your DJ Account" %>
   <% end %>
<% else %>
   <p>Hey, looks like you're logged in as
   <%= current_user.dj_name %>. Did you want to
   <%= link_to 'edit your profile?', edit_user_path(current_user) %> instead?</p>
<% end %>

app/views/users/show.html.erb
<% back_path = URI(request.referer).path %>

<div class="user" id="details">
   <h1>DJ: <%= @user.dj_name %></h1>
   <%= image_tag @user.avatar, class: "user-avatar" %>
</div>

<div class="user-collection">
   <% if current_user && (@user.id == current_user.id) %>
      <h2>Your Collection</h2>
   <% else %>
      <h2><%= @user.dj_name %>'s Collection</h2>
   <% end %>

   <div class="mixtapes-list">
      <h3>Display Mixtapes</h3>
      <%= render partial: 'my_mixtapes', :locals => { :collection => @user.mixtapes } %>
   </div>

   <div class="song-list">
      <h3>Display Songs</h3>
      <%= render partial: 'my_songs', :locals => { :collection => @user.songs }  %>
      </p>
   </div>
</div>

<%# Navigation %>
<div class="actions-bot">
   <h2>Actions:</h2>
   <%= link_to "<< Back", back_path %>
   <%= link_to "DJ List", users_path %>
   <% if !current_user %>
      <%# Nag for login %>
      <%= render partial: 'layouts/hey_dj' %> to start Mix.ing!</p>
   <% end %>
</div>