config/routes.rb
Rails.application.routes.draw do

   root 'welcome#index'

   get '/login' => 'sessions#new'
   post '/login' => 'sessions#create'
   get '/logout' => 'sessions#destroy' #, as: 'logout'

   get '/signup' => 'users#new' #, as: 'signup'
   post '/users' => 'users#create'

   resources :users

   resources :mixtapes do
      member do
         post 'record_song'
         get 'erase_song'
      end
   end

   resources :songs

end

app/models/mixtape.rb
class Mixtape < ActiveRecord::Base
   belongs_to :user

   has_and_belongs_to_many :songs

   validates :name, presence: true, uniqueness: {
      case_sensitive: false,
      message: "is taken buddy. Mix it up!" }


   def add_error(string)
      self.errors.messages.store(:whoops,string)
   end

   def record(song)
      starting = self.songs.length
      if self.songs = (self.songs + [song]).uniq
      end
      ending = self.songs.length

      if ending == starting
         self.add_error("That song is already on your Mixtape! Choose another from the list!")
      end
   end

   def erase(song)
      self.songs.destroy(song)
   end

   # validate urls. look at work on blogger
   # def tag_list=(tags_string)
   #    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
   #    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
   #    self.tags = new_or_found_tags
   # end
   #
   # def tag_list
   #   tags.join(", ")
   # end


end

app/controllers/mixtapes_controller.rb
class MixtapesController < ApplicationController

   before_filter :authorize, except: [:index, :show]

   def index
      @mixtapes = Mixtape.all
   end

   def show
      @mixtape = Mixtape.find(params[:id])
      @song = Song.new
   end

   def new
      @mixtape = Mixtape.new
   end

   def create
      @mixtape = Mixtape.new(mixtape_params)
      @mixtape.user_id = current_user.id

      if @mixtape.save
         flash.notice = "#{@mixtape.name}!? Nice! "
         redirect_to mixtape_path(@mixtape)
      else
         render 'new'
      end
   end

   def edit
      @mixtape = Mixtape.find(params[:id])
   end

   def update
      @mixtape = Mixtape.find(params[:id])

      if @mixtape.update(mixtape_params)
         flash.notice = "'#{@mixtape.name}' Updated! Mixin' up a storm 'ova hea'! "
         redirect_to mixtape_path(@mixtape)
      else
         render 'show'
      end
   end

   def destroy
      @mixtape = Mixtape.find(params[:id])

      if @mixtape.destroy
         flash.notice = "'#{@mixtape.name}' Mixtape Deleted! "
         redirect_to mixtapes_path
      else
         render 'show'
      end
   end

   def record_song
      song = Song.find(params[:mixtapes_songs][:song_id])

      # access mixtape correctly depending on referrer:
      if ( URI(request.referer).path.match '/songs/' )
         mixtape = Mixtape.find(params[:mixtapes_songs][:mixtape_id])
      else
         mixtape = Mixtape.find(params[:id])
      end

      mixtape.record(song)
      flash[:error] = mixtape.errors[:whoops]
      flash.notice = "#{song.title} mix.d in! " if flash[:error] == []
      redirect_to mixtape_path(mixtape)
   end

   def erase_song
      mixtape = Mixtape.find(params[:id])
      mixtape.erase(Song.find(params[:song_id]))

      flash.notice = "#{song.name} erased from this Mixtape. "
      redirect_to mixtape_path(mixtape)
   end

   private

   def mixtape_params
      params.require(:mixtape).permit(
      :name,
      :dedication,
      :about,
      :img_src,
      :user_id,
      :mixtape_songs,
      :song_id,
      :song
      )
   end

end

app/views/mixtapes/_dd_failure.html.erb
<% if flash[:error] != [] %>
   <div class="errors">
      <p class="error"><%= flash[:error] %><p>
   </div>
<% end %>

app/views/mixtapes/_display.html.erb
<div class="mixtapes">
   <% @mixtapes.each do |mixtape| %>
      <% if mixtape.id != 42 %>
         <% user = User.find(mixtape.user_id) %>
         <div class="tapes">
            <h1><%= link_to mixtape.name, mixtape_path(mixtape), class: 'mixtape_name', id: "mixtape_#{mixtape.id}" %></h1>
            <p>(<%= mixtape.songs.length %>) Songs about: <%= mixtape.about %></p>
            <p>Posted <%= distance_of_time_in_words(DateTime.now, mixtape.created_at) %> ago by <%= link_to user.dj_name, user_path(user) %></p>
         </div>
      <% end %>
   <% end %>
</div>

app/views/mixtapes/_form.html.erb
<% if current_user %>
   <div class="create" id="mixtape">
      <%= form_for [ @mixtape ] do |f| %>
        <p class="field">
          <%= f.label "What's the name of this Mix? *" %><br/>
          <%= f.text_field :name %>
        </p>

        <p class="field">
          <%= f.label "Is this dedicated to a special someone?" %><br/>
          <%= f.text_field :dedication %>
        </p>

        <p class="field">
          <%= f.label "What's your theme?" %><br/>
          <%= f.text_area :about %>
        </p>

        <p class="field">
          <%= f.label "Paste a new Image URL" %><br/>
          <%= f.text_field :img_src %>
        </p>

        <p class="field" id="art-display">Current Image:
           <br><%= image_tag @mixtape.img_src %>
        </p>
        
        <p class="field" id="submit">
          <%= f.submit 'Submit' %>
        </p>
      <% end %>
   </div>
<% end %>

app/views/mixtapes/_song.html.erb
<div class="song">
  <p class="song-info"><span class="italic"><%= song.title %></span> by <%= song.artist %>
  <span class="song-links"><%= link_to "Play", song.audio %> <%= link_to "Info", song_path(song) %> <%= link_to "Erase from Mixtape", erase_song_mixtape_path(:id => @mixtape.id, :song_id => song) %> ...Posted <%= distance_of_time_in_words(DateTime.now, song.created_at) %> ago</p>

</div>

app/views/mixtapes/_song_add.html.erb
<% if current_user %>
   <%= form_for [@song] do |f| %>
      <p class="field">
         <%= f.label "Title, Ex: Shake it Off *" %><br/>
         <%= f.text_field :title %>
      </p>
      <p class="field">
         <%= f.label "Artist, Ex: Dolly Parton *" %><br/>
         <%= f.text_field :artist %>
      </p>
         <%= f.label "Album, Ex: Thriller" %><br/>
         <%= f.text_field :album %>
      </p>
      <p class="field">
         <%= f.label "Date of Album/Single Release date." %><br/>
         <%= f.date_select :date_released, prompt: true, start_year: 2015, end_year: 1900, discard_day: true, include_blank: true %>
      </p>
      <p class="field">
         <%= f.label "Audio aka Youtube URL *" %><br/>
         <%= f.text_field :audio %>
         <p id="youtube-instructions">
            Just place the regular old youtube url from the address bar! into the field above!
         </p>
      </p>
         <%= f.hidden_field :mixtape_id, :value => @mixtape.id %>
      <p class="field" id="submit">
        <%= f.submit "Add to #{@mixtape.name}" %>
      </p>
   <% end %>
<% end %>

app/views/mixtapes/_song_select.html.erb
<% if current_user %>
   <% if Song.all.length > 1 %>
      <%= form_for :mixtapes_songs, url: record_song_mixtape_path do |f| %>

         <p class="field" id="drop-down">
            <%= f.label "Choose a song from the Mix.r Library" %><br/>
            <%= f.collection_select(:song_id, Song.all, :id, :title) %>
         </p>
            <%= f.hidden_field :mixtape_id, :value => @mixtape.id%>
         <p class="field" id="submit">
            <%= f.submit "Add song to #{@mixtape.name}"%>
         </p>

      <% end %>
   <% end %>
<% end %>

app/views/mixtapes/edit.html.erb
<h3>Edit <%= @mixtape.name %></h3>

<%# Creator can edit %>
<% if current_user && current_user.id == @song.user_id %>
   <%= render partial: 'form' %>

<%# Edit only your content %>
<% elsif current_user  %>
   <p class="errors" id="error-details">You can only edit Mixtapes you have added.</p>
   <div class="actions-bot">
      <%# Navigation/Actions if logged in %>
      <h3>Actions</h3>
      <%= link_to "<< Back", back_path %>
      <%= link_to "Create a New Mixtape", new_mixtape_path, class: "new", id: "mixtape" %>
   </div>
<%# Nag for login %>
<% else %>
   <%= render partial: 'layouts/hey_dj' %> make edits. Sneaky, sneaky.</p>
<% end %>

app/views/mixtapes/index.html.erb
<h1>All Mixtapes</h1>

<%= render partial: 'mixtapes/display' %>

<%# Navigation %>
<div class="actions-bot">
   <% if current_user %>
      <%= link_to "Create a New Mixtape", new_mixtape_path, class: "new", id: "mixtape" %>
   <% else %>
      <%# Nag for login %>
      <%= render partial: 'layouts/hey_dj' %> to record your own Mixtapes!</p>
   <% end %>
</div>

app/views/mixtapes/new.html.erb
<h3>Create a Mixtape</h3>

<% if current_user %>
   <%= render partial: 'layouts/errors', :locals => { :noun => @mixtape } %>
   <%= render partial: 'form' %>
<% else %>
   <%# Nag for login %>
   <%= render partial: 'layouts/hey_dj' %> to add and edit your own Mixtapes SNEAKY!!</p>
<% end %>

app/views/mixtapes/show.html.erb
<% back_path = URI(request.referer).path %>

<div class="mixtape">
   <div class="one">
      <h1 class="mixtape" id="name"><%= @mixtape.name %></h1>
      <p><%= image_tag @mixtape.img_src %></p>
   </div>

   <div class="spine">
      <h3><%= @mixtape.name %> has: (<%= @mixtape.songs.size %>) Songs</h3>
   </div>
   <div class="two">
      <p><%= @mixtape.about %></p>
      <p><%= @mixtape.dedication %></p>
   </div>


   <div class="mixtape-song-list">
      <%= render partial: 'mixtapes/song', collection: @mixtape.songs %>
   </div>

   <%# Logged in user can add and create songs %>
   <% if current_user %>
      <div id="add-song-divider"></div>

      <div class="song-add-select" id="mixtape">
         <%# Add from library via drop-down menu %>
         <h3>Add a Song to <span class="mixtape" id="name"><%= @mixtape.name %>!</span></h3>
         <%# ERROR DISPLAY: tried to add a duplicate song via drop down %>
         <%= render partial: 'mixtapes/dd_failure', :locals => { :noun => @mixtape } %>
         <%# Select song %>
         <%= render partial: 'mixtapes/song_select' %>
      </div>

      <div class="song-add-form">
         <%# Add song to library and mixtape via form %>
         <%# ERROR DISPLAY: mistakes from adding via song form %>
         <% if @song %>
            <%= render partial: 'layouts/errors_flash', :locals => { :noun => flash[:errors] } %>
         <% end %>
         <%# New song form%>
         <%= render partial: 'mixtapes/song_add' %>
      </div>
   <% else %>
      <%# Nag for login %>
      <%= render partial: 'layouts/hey_dj' %> to add songs to this Mixtape.
   <% end %>
</div>

<div class="actions-bot">
   <%# Navigation/Actions if logged in %>
   <h3>Actions</h3>
      <%= link_to "<< Back", back_path %>
   <% if current_user %>
      <%= link_to "Edit Mixtape", edit_mixtape_path(@mixtape) %>
      <%= link_to "Delete Mixtape", mixtape_path(@mixtape), method: :delete, data: {confirm: "Really delete the mixtape?"} %>
   <% else %>
      <%# Nag for login %>
      <%= render partial: 'layouts/hey_dj' %> to add and edit your own Mixtapes!</p>
   <% end %>
</div>