config/routes.rb
Rails.application.routes.draw do

   root 'welcome#index'

   get '/login' => 'sessions#new'
   post '/login' => 'sessions#create'
   get '/logout' => 'sessions#destroy' #, as: 'logout'

   get '/signup' => 'users#new' #, as: 'signup'
   post '/users' => 'users#create'

   resources :users

   resources :mixtapes do
      member do
         post 'record_song'
         get 'erase_song'
      end
   end

   resources :songs

end

app/models/song.rb
class Song < ActiveRecord::Base
   belongs_to :user

   has_and_belongs_to_many :mixtapes
   # has_many :song_facts

   validates :title, :artist, :audio, presence: true

   validates :title, uniqueness: { scope: :artist,
      case_sensitive: false,
      message: "matches a song that is already in the Mix.r Library. \n Add it from the drop-down instead!" }

   # validates :audio

   def fix_url(string)
      self.audio = string.sub! 'watch?v=', 'v/'
   end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

   before_filter :authorize, except: [:index, :show]

   def index
      @songs = Song.order(created_at: :desc)
   end

   def new
      @song = Song.new
   end

   def create
      # Different actions depending where song was created
      # Coming from mixtape, sanitize params!
      if params[:song][:mixtape_id]
         if params[:song][:mixtape_id] != "42"
            @mixtape = Mixtape.find(params[:song][:mixtape_id])
         end
         params[:song].delete(:mixtape_id)
      end

      @song = Song.new(song_params)
      @song.fix_url(params[:song][:audio])
      @song.user_id = current_user.id

      # Verify redirects and actions based on URL referrer
      add_from_mix(URI(request.referer).path,@mixtape,@song)
	end

   def edit
      @song = Song.find(params[:id])
   end

   def update
      @song = Song.find(params[:id])
      @song.update(song_params)

      redirect_to song_path(@song)
   end

   def show
      @song = Song.find(params[:id])
   end

   def destroy
      path = params[:path] # get path for redirect
      params.delete(:path) # sanitize params

      @song = Song.find(params[:id])

      # if song is used on mixtapes, remove:
      if @song.mixtapes.length > 0
         @song.mixtapes.each { |m| m.erase(@song) }
      end

      @song.destroy

      # can only destroy song from song detail view
      # redirect based on how you got to view
      redirect_to path
   end

   private

   def add_from_mix(path,mixtape,song)
      # Coming from a mixtape:
      if ( path.match '/mixtapes/' ) && song.save
         mixtape.record(song) # record song to mixtape it came from
         # flash[] = "You added #{song.title} by #{song.artist} to #{mixtape.name}! Rock on!"
         redirect_to path #success
      elsif path.match '/mixtapes/'
         redirect_to path, flash: {errors: song.errors}
      # song made as standalone
      elsif song.save
         redirect_to song_path(song) # success
      else
         render 'new' # song made as standalone, unsuccessful
      end
   end

   def song_params
     params.require(:song).permit(
     :title,
     :artist,
     :album,
     :date_released,
     :audio,
     :user_id,
     :mixtapes_songs,
     :mixtape_id,
     )
   end

end

app/views/songs/_display.html.erb
<div class="songs">
   <% @songs.each do |song| %>
   <% user = User.find(song.user_id) %>
   <div class="song">
      <p class="song-info"><span class="italic"><%= song.title %></span> by <%= song.artist %></p>

      <%= render partial: 'songs/play_button', :locals => { :song => song }%>
      <p class="links">
      <%= link_to "View Song Details", song_path(song) %> Posted <%= distance_of_time_in_words(DateTime.now, song.created_at) %> ago by <%= link_to user.dj_name, user_path(user), class: "dj" %> </p>
   </div>
   <% end %>
</div>

app/views/songs/_form.html.erb
<%= form_for [ @song ] do |f| %>
   <p class="field">
      <%= f.label "Title, Ex: Shake it Off*" %><br/>
      <%= f.text_field :title %>
   </p>

   <p class="field">
      <%= f.label "Artist, Ex: Dolly Parton*" %><br/>
      <%= f.text_field :artist %>
   </p>

   <p class="field">
      <%= f.label "Album, Ex: Thriller" %><br/>
      <%= f.text_field :album %>
   </p>
   <p class="field" id="select">
      <%= f.label "Date of Album/Single Release date." %><br/>
      <%= f.date_select :date_released, prompt: true, start_year: 2015, end_year: 1900, discard_day: true, include_blank: true %>
   </p>
   <p class="field" id="audio">
      <%= f.label "Audio aka Youtube URL *" %><br/>
      <%= f.text_field :audio %>
      <p id="youtube-instructions">
         Just place the regular old youtube url from the address bar! into the field above!
      </p>
   </p>
   <!-- <p class="field" id="select"> -->
      <%# f.label "Add this song to a mixtape:" %>
      <!-- <br> -->
      <%# f.collection_select(:mixtape_id, Mixtape.all, :id, :name, {prompt: "Select a mixtape"}) %>
   <!-- </p> -->
   <p class="field" id="submit">
      <%= f.submit "Submit Song to Mix.r Library" %>
   </p>
<% end %>

app/views/songs/_mixtape_select.html.erb
<%= form_for :mixtapes_songs, url: record_song_mixtape_path do |f| %>
   <%= f.label "Add this song to a mixtape:" %><br/>
   <%= f.collection_select(:mixtape_id, Mixtape.all, :id, :name) %>
   <%= f.hidden_field :song_id, :value => @song.id%>
   <%= f.submit "Add song to a Mixtape!"%>
<% end %>

app/views/songs/_play_button.html.erb
<div class="play">
   <div class="play-button"></div>
   <iframe class="play-vid" src="<%= "#{song.audio}?&amp;iv_load_policy=3&amp;rel=0&amp;controls=0&amp;showinfo=0" %>"  frameborder="0" allowfullscreen></iframe>
</div>

app/views/songs/edit.html.erb
<h3>Edit <%= @song.title %></h3>

<%# Creator can edit %>
<% if current_user && current_user.id == @song.user_id %>
   <%= render partial: 'form' %>

<%# But not creepers %>
<% elsif current_user %>
   <p class="errors" id="error-details">You can only edit Songs you have added.</p>
   <div class="actions-bot">
      <%# Navigation/Actions if logged in %>
      <h3>Actions</h3>
      <%= link_to "<< Back", back_path %>
      <%= link_to "Add a Song to Mix.r Library", new_song_path, class: "new", id: "song" %>
   </div>

<%# Or lurkers %>
<% else %>
   <%# Nag for login %>
   <%= render partial: 'layouts/hey_dj' %>wtf how do you even?</p>
<% end %>

app/views/songs/index.html.erb
<h1>Mix.r Song Library</h1>

<%= render partial: 'songs/display' %>

<%# Navigation %>
<div class="actions-bot">
   <% if current_user %>
      <%= link_to "Add a Song to Mix.r Library", new_song_path, class: "new", id: "song" %>
   <% else %>
      <%= render partial: 'layouts/hey_dj' %> to add a new song to the Mix.r Library.</p>
   <% end %>
</div>

app/views/songs/new.html.erb
<%= render partial: 'layouts/errors', :locals => { :noun => @song } %>

<% if current_user %>
   <%= render partial: 'form' %>
<% else %>
   <%# Nag for login %>
   <%= render partial: 'layouts/hey_dj' %></p>
<% end %>

app/views/songs/show.html.erb
<% back_path = URI(request.referer).path %>
<% user = User.find(@song.user_id) %>

<div class="song">
  <p class="song-info"><span class="italic"><%= @song.title %></span> by <%= @song.artist %></p>
  <p class="song-history">From "<%= @song.album %>", Released <%= @song.date_released %></p>
  <p class="song-stats">Posted <%= distance_of_time_in_words(DateTime.now, @song.created_at) %> ago

  <%= link_to "Play", @song.audio, :target => "_blank" %>
  <p>Posted <%= distance_of_time_in_words(DateTime.now, @song.created_at) %> ago</p>
      <p>by <%= link_to user.dj_name, user_path(user) %></p>
</div>


<!-- <h2>Song Facts:</h2>
<p>nothing for now.</p> -->

<div class="song-actions">
   <% if current_user %>
      <%# Add song to mixtape via drop down menu %>
      <% if Mixtape.all.length > 1 %>
         <%= render partial: 'mixtape_select' %>
      <% end %>
   <% else %>
      <%# Nag for login %>
      <%= render partial: 'layouts/hey_dj' %> to add this song to a Mixtape of your own!</p>
   <% end %>
</div>

<%# Navigation %>
<div class="actions-bot">
   <h2>Actions:</h2>
   <%= link_to "<< Back", back_path %>
   <% if !current_user %>
      <%# Nag for login %>
      <%= render partial: 'layouts/hey_dj' %> to add and edit your own songs!</p>
   <% elsif current_user.id == @song.user_id %>
      <%# Creator can edit/delete %>
      <%= link_to "Edit Song", edit_song_path(@song) %>
      <%= link_to "Delete Song", song_path(:id => @song.id, :path => back_path), method: :delete, data: {confirm: "Really delete the song?"} %>
   <% end %>
</div>