config/routes.rb
Rails.application.routes.draw do

   root 'welcome#index'

   get '/login' => 'sessions#new'
   post '/login' => 'sessions#create'
   get '/logout' => 'sessions#destroy' #, as: 'logout'

   get '/signup' => 'users#new' #, as: 'signup'
   post '/users' => 'users#create'

   resources :users

   resources :mixtapes do
      member do
         post 'record_song'
         get 'erase_song'
      end
   end

   resources :songs

end

app/views/layouts/_errors.html.erb
<%# display default errors %>
<% if noun && noun.errors.messages.length > 0 %>
   <div class="errors">
      <% noun.errors.full_messages.each do |error_msg| %>
         <li class="error" id="error-detail"><%= error_msg %></li>
      <% end %>
   </div>
<% end %>

app/views/layouts/_errors_flash.html.erb
<%# display custom/funny errors %>
<% if noun && noun.length > 0 %>
   <div class="errors">
      <% noun.each do |obj,errors| %>
         <li class="error"><%= obj.capitalize %>:
            <% errors.each do |m| %>
               <p id="error-detail"><%= m %></p>
            <% end %>
         </li>
      <% end %>
   </div>
<% end %>

app/views/layouts/_hey_dj.html.erb
<%# display nag to login when browsing as guest %>
<p class="nag">Hey DJ, <%= link_to 'Login', '/login' %> or <%= link_to 'Create a DJ Account', '/signup' %>

app/views/layouts/_nav_top.html.erb
<%# top navigation bar %>
<div class="top-block">
   <div class="nav-top">
      <%= link_to 'Home', '/' %>
      <%= link_to 'Mixtapes', mixtapes_path %>
      <%= link_to 'Songs', songs_path %>
      <%= link_to 'Browse DJs', users_path %>
      <%# link_to 'Hall of Fame', '/' %>

      <%# nag for login %>
      <% if !current_user %>
         <%= link_to 'Login', '/login', class: 'blink'%>
         <%= link_to 'Create a DJ Account', '/signup'%></span>
      <% end %>
   </div>
</div>

app/views/layouts/_notices_flash.html.erb
<%# display custom success notices with links %>
<% if !flash.notice.nil? %>
   <p class="flash-notices"><%= flash.notice %>
      <%# different links depending on success notices %>
      <%=link_to('Now let\'s add some songs!', :anchor => "add-song-divider") if flash.notice.end_with?('Nice! ')%>
      <%=link_to('Keep it going, DJ!', :anchor => "add-song-divider") if flash.notice.end_with?('mix.d in! ')%>
      <%=link_to('Add a new Mixtape?', new_mixtape_path) if flash.notice.end_with?('e Deleted! ')%>
      <%=link_to('Add a new Song to Mix.r?', new_song_path) if flash.notice.end_with?('g Deleted! ')%>
      <%=link_to('Add it to a different mixtape?', mixtapes_path) if flash.notice.end_with?('from this Mixtape. ')%>
   </p>
<% end %>

app/views/layouts/_sidebar.html.erb
<% if current_user %>
   <div id="sidebar">
        <ul id="side-links">
           <div class="side-divide" id="first"></div>
           <!-- Salutation -->
           <%= "Yo #{current_user.dj_name}!" %>

           <div class="side-divide"></div>
           <!-- Navigation -->
           <li><%= link_to 'Create a New Mixtape', new_mixtape_path(current_user) %></li>
           <li><%= link_to 'Add Song to the Mix.r Library', new_song_path(current_user) %></li>

           <div class="side-divide"></div>
           <li><%= link_to 'View Your Profile', user_path(current_user) %></li>
           <li><%# link_to 'Favorite DJs?', users_path %></li>

           <div class="side-divide"></div>
           <li><%= link_to 'Account Details', edit_user_path(current_user) %></li>

           <div class="side-divide"></div>
           <li><%= link_to 'Logout', '/logout' %></li>

           <div class="side-divide" id="last"></div>
        </ul>
   </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MymixApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="logo">
   <h1 id="icon">Mix<span class="whoosh">.r</span></h1>
   <p id="tagline">mix it up</p>
</div>
<%= render partial: 'layouts/nav_top' %>
<%= render partial: 'layouts/sidebar' %>

<div id="app">
   <%= render partial: 'layouts/notices_flash' %>
   <%= yield %>
</div>

<div class="nav-bot">
   <p id="copyright">Dear interwebs, Layout designed FROM FUCKING SCRATCH by Rachel Smyth. (c) 2015, because templates are cheating.</p>
</div>
</body>
</html>